### ISSUE TITLE
[Question] How to use it?

### ISSUE THREAD

**Issue by bogwro** [openfrontier/ci-compose#1]
I am interested in setting-up CI with Gerrit where all of the services are defined in `docker-compose.yml`

I found your project very interesting.

With the spirit of `Do not re-invent the wheel...` I would like to use your solution and customise it to my needs.

Your `docker-compose.yml` [file](https://github.com/openfrontier/ci-compose/blob/master/docker-compose.yml) looks good but depends on many ENV Variables and I think the most important file is missing; based on content of `ci.sh` [file](https://github.com/openfrontier/ci-compose/blob/master/ci.sh):

```
source ./config

docker-compose ${COMPOSE_OPT} $@
```

**There is no `config` file in the repository.**

I have identified following ENV Variables just by analysing `docker-compose.yml` file.

```
CI_INIT_ADMIN
CI_INIT_PASSWORD
GERRIT_VERSION
JENKINS_AGENT_LABEL
JENKINS_VERSION
LDAP_GROUP_BASEDN
LDAP_ROOTDN
LDAP_URI
PROXY_HOST
PROXY_NODE
```

... and I assume they should be defined in `config` file like:

```
export CI_INIT_ADMIN=admin
export CI_INIT_PASSWORD=p@ssw0rd
export GERRIT_VERSION=2.12.x
export JENKINS_AGENT_LABEL=slave
export JENKINS_VERSION=2.19.2-alpine
export LDAP_GROUP_BASEDN= (???)
export LDAP_ROOTDN= (???)
export LDAP_URI= (???)
export PROXY_HOST=(???)
export PROXY_NODE= (???)
```

Most of them are easy to guess what value to set... but not all of them.

However... I tried and it does not work for me after:

```
git clone https://github.com/openfrontier/ci-compose.git
# next I defined env variables in `config` file, then
chmod +x ./ci.sh
./ci.sh up
# it starts `docker-compose up` normally and exits with error after some time...
```

Expected behavior:  executed command finishes successfully

---

In [current set-up](https://github.com/openfrontier/ci-compose/blob/master/docker-compose.yml) LDAP is in use. 

Could you provide different configurations of services by creating multiple `docker-compose-config[A...Z].yml` files - starting with the easiest set-up just to have it up & running locally by executing `docker-compose up` thru more complex ones like: 

- `docker-compose -f docker-compose-configA up`
- `docker-compose -f docker-compose-configB up`

I would suggest to use [env_file](https://docs.docker.com/compose/compose-file/#/envfile) in each compose yaml file and delete `config` file.

> Ultimately I would like to use Google Accounts / Apps OAuth2 to authenticate / authorise users. I have it integrated with Jenkins via `google-login` plug-in.

> I am willing to contribute back once I have it up & running with minimum set-up

**Comment by thinkernel** [comment]
In case you have used the latest images, I found a bug in the [events-log plugin](https://gerrit.googlesource.com/plugins/events-log/) which is caused by a [recent commit](https://github.com/thinkernel/events-log/commit/579dad1001d1368054077587ec68f1ac74aaaa7c) on that project. This bug is preventing openfrontier/gerrit from working properly. I need to figure out a work-around first then I will see how can make this compose project more useful as you advised.

**Comment by thinkernel** [comment]
I made some updates. An instruction is added in the README. I change the name of config to env.config and add some comments in the file in order to make it easier for people to decide how to use it.

**Comment by frederic-gendebien** [comment]
Hello guys, I am testing your ci-compose demo and I was wondering if it was possible to add an OpendLDAP ready for the demo?

**Comment by thinkernel** [comment]
I'm working on it.  The problem is that I have to ensure the openldap is full started before other services in CI is started. Compose's dependence doesn't work in this level.
BTW: Thanks for the patch for the openldap-docker project.

**Comment by thinkernel** [comment]
@frederic-gendebien 
I added a separated compose file for openldap and lam(For adding or importing user into the openldap). The README is updated with the instructions.
