### ISSUE TITLE
unable to login to apps

### ISSUE THREAD

**Issue by builderall** [openfrontier/ci-compose#2]
Hi, Thanks much for the great lab setup code. I was able to install it in a vagrant box (https://atlas.hashicorp.com/joelhandwell/boxes/dockerhost).  I am able to access LAM gui and update admin password and create "accounts" and "groups" OU. Also the OCIP dashboard shows up!! However cannot login to any of the apps using "admin" ID and password (updated to env.config entry in LAM gui).

What could be wrong?

Thanks much.

**Comment by builderall** [comment]
Here are some syslog entries for gerrit:

Apr  5 03:57:08 default dockerd[1268]: gerrit:8080/gerrit ready
Apr  5 03:57:08 default dockerd[1268]: waiting for jenkins:8080/jenkins to be available
Apr  5 03:57:09 default dockerd[1268]: jenkins:8080/jenkins ready
Apr  5 03:57:09 default dockerd[1268]: waiting for nexus:8081/nexus to be available
Apr  5 03:57:09 default dockerd[1268]: 2017-04-05 03:57:09,978+0000 INFO  [qtp836514715-76] *SYSTEM org.apache.shiro.nexus5727.FixedDefaultWebSessionManager - Global session timeout: 1800000 ms
Apr  5 03:57:09 default dockerd[1268]: 2017-04-05 03:57:09,979+0000 INFO  [qtp836514715-76] *SYSTEM org.apache.shiro.session.mgt.AbstractValidatingSessionManager - Enabling session validation scheduler...
Apr  5 03:57:10 default dockerd[1268]: 2017-04-05 03:57:10,066+0000 INFO  [qtp836514715-76] *UNKNOWN org.sonatype.nexus.velocity.VelocityEngineProvider - Creating Nexus VelocityEngine
Apr  5 03:57:10 default dockerd[1268]: nexus:8081/nexus ready
Apr  5 03:57:10 default dockerd[1268]: waiting for redmine/redmine to be available
Apr  5 03:57:10 default dockerd[1268]: redmine/redmine unavailable, sleeping for 5
Apr  5 03:57:10 default dockerd[1268]: Apr 05, 2017 11:57:10 AM com.sonymobile.tools.gerrit.gerritevents.GerritConnection connect
Apr  5 03:57:10 default dockerd[1268]: SEVERE: Could not connect to Gerrit server! Host: gerrit Port: 29418
Apr  5 03:57:10 default dockerd[1268]: Apr 05, 2017 11:57:10 AM com.sonymobile.tools.gerrit.gerritevents.GerritConnection connect
Apr  5 03:57:10 default dockerd[1268]: SEVERE:  Proxy:
Apr  5 03:57:10 default dockerd[1268]: Apr 05, 2017 11:57:10 AM com.sonymobile.tools.gerrit.gerritevents.GerritConnection connect
Apr  5 03:57:10 default dockerd[1268]: SEVERE:  User: jenkins KeyFile: /var/jenkins_home/.ssh/id_rsa
Apr  5 03:57:10 default dockerd[1268]: Apr 05, 2017 11:57:10 AM com.sonymobile.tools.gerrit.gerritevents.GerritConnection connect
Apr  5 03:57:10 default dockerd[1268]: SEVERE: IOException:
Apr  5 03:57:10 default dockerd[1268]: com.sonymobile.tools.gerrit.gerritevents.ssh.SshException: com.jcraft.jsch.JSchException: Auth fail
Apr  5 03:57:10 default dockerd[1268]: #011at com.sonymobile.tools.gerrit.gerritevents.ssh.SshConnectionImpl.connect(SshConnectionImpl.java:181)
Apr  5 03:57:10 default dockerd[1268]: #011at com.sonymobile.tools.gerrit.gerritevents.ssh.SshConnectionFactory.getConnection(SshConnectionFactory.java:98)
Apr  5 03:57:10 default dockerd[1268]: #011at com.sonymobile.tools.gerrit.gerritevents.GerritConnection.connect(GerritConnection.java:391)
Apr  5 03:57:10 default dockerd[1268]: #011at com.sonymobile.tools.gerrit.gerritevents.GerritConnection.run(GerritConnection.java:317)
Apr  5 03:57:10 default dockerd[1268]: Caused by: com.jcraft.jsch.JSchException: Auth fail
Apr  5 03:57:10 default dockerd[1268]: #011at com.jcraft.jsch.Session.connect(Session.java:512)
Apr  5 03:57:10 default dockerd[1268]: #011at com.jcraft.jsch.Session.connect(Session.java:183)
Apr  5 03:57:10 default dockerd[1268]: #011at com.sonymobile.tools.gerrit.gerritevents.ssh.SshConnectionImpl.connect(SshConnectionImpl.java:177)
Apr  5 03:57:10 default dockerd[1268]: #011... 3 more
Apr  5 03:57:10 default dockerd[1268]:
Apr  5 03:57:11 default dockerd[1268]: Creating user: admin
Apr  5 03:57:11 default dockerd[1268]: 58e46b17 conn=1061 fd=15 ACCEPT from IP=172.18.0.9:43630 (IP=0.0.0.0:389)
Apr  5 03:57:11 default dockerd[1268]: 58e46b17 conn=1061 op=0 BIND dn="" method=128
Apr  5 03:57:11 default dockerd[1268]: 58e46b17 conn=1061 op=0 RESULT tag=97 err=0 text=
Apr  5 03:57:11 default dockerd[1268]: 58e46b17 conn=1061 op=1 SRCH base="" scope=0 deref=3 filter="(objectClass=*)"
Apr  5 03:57:11 default dockerd[1268]: 58e46b17 conn=1061 op=1 SEARCH RESULT tag=101 err=0 nentries=1 text=
Apr  5 03:57:11 default dockerd[1268]: 58e46b17 conn=1061 op=2 SRCH base="ou=accounts,dc=lab,dc=lan" scope=2 deref=3 filter="(uid=admin)"
Apr  5 03:57:11 default dockerd[1268]: 58e46b17 conn=1061 op=2 SRCH attr=uid mail givenName gidNumber sn username
Apr  5 03:57:11 default dockerd[1268]: 58e46b17 conn=1061 op=2 SEARCH RESULT tag=101 err=0 nentries=0 text=
Apr  5 03:57:11 default dockerd[1268]: 58e46b17 conn=1061 op=3 UNBIND
Apr  5 03:57:11 default dockerd[1268]: 58e46b17 conn=1061 fd=15 closed
Apr  5 03:57:11 default dockerd[1268]: [2017-04-05 03:57:11,812] [HTTP-84] INFO  com.google.gerrit.httpd.auth.ldap.LdapLoginServlet : 'admin' failed to sign in: No such user: admin
Apr  5 03:57:11 default dockerd[1268]: Unable to create user admin, response code 401, retry ... 0
Apr  5 03:57:13 default dockerd[1268]: Apr 05, 2017 11:57:13 AM com.sonymobile.tools.gerrit.gerritevents.GerritConnection connect

**Comment by builderall** [comment]
Sorry, I did not define "admin" user in LDAP (got confused LDAP ADMIN with same id). As soon as created the user , now can login into Jenkins and gerrit. Thanks much, Need to figure out redmine/nexus

**Comment by thinkernel** [comment]
redmine: admin/admin
nexus: admin/admin123
